#!/bin/bash

# Devel machines
export DEVEL=devel.asvglobal.com
export DEVELUS=devel-source.asvus.com

# Mercurial Repositories
export HGREPO=ssh://$DEVEL//devel/src/hg-repository
export HGREPO_TMP=ssh://$DEVEL//devel/unmanned
export HGREPO_US=ssh://$DEVELUS//data/source
export HGREPO_US_TMP=ssh://$DEVELUS//data/source-testing

# Git repository for interview questions
export CCTREPO=https://thompson_christopher_c@bitbucket.org/thompson_christopher_c

# Lazy
alias la='ls -a'
alias ll='ls -l'
alias lla='ls -la'
alias qmake='qmake-qt5'
alias qmaked='qmake-qt5 -r -config debug'

# Set history size much higher than normal
export HISTSIZE=15000

# Setup tmuxinator
export PATH=$PATH:~/tools/tmuxinator/bin
alias mux='tmuxinator'

export EDITOR=emacs

# Qt logging rules
export QT_LOGGING_RULES="*.debug=true;qt.*.debug=false"
export QT_MESSAGE_PATTERN="`echo -e "%{if-category}|\033[32m%{category}\033[0m|%{endif}%{message} %{if-warning}(%{file}:%{line})%{endif}%{if-critical}%{backtrace}%{endif}%{if-fatal}%{backtrace}%{endif}"`"
