#!/usr/bin/bash

# Set history size much higher than normal
export HISTSIZE=15000

# Setup local paths
PATH=$PATH:$HOME/.bin
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/lib

PYTHONPATH=$PYTHONPATH:.

# Setup local modulefiles
MODULEPATH=$MODULEPATH:$HOME/.modulefiles

export EDITOR=emacs
