#!/usr/bin/bash

# Lazy
alias la='ls -a'
alias ll='ls -lh'
alias lla='ls -lha'
alias qmake='qmake-qt5 -r CONFIG+="release DEV_BUILD"'
alias qmaked='qmake-qt5 -r CONFIG+="debug coverage DEV_BUILD"'
alias pp='pushd'
alias po='popd'

# Fat-fingers
alias qhg='hg'
alias qgit='git'

# Clear any core files found in any subdir
alias cct-clear-cores='find . -regextype posix-extended -regex ".*core\.[0-9]+" -exec rm {} \;'

# Make the world
alias cct-make-install='make -sj8 && make install -sj8'

# Use emacs server
alias emacs='emacsclient -c -a emacs -q &'

# Support neovim
alias vim='echo "I am sorry you have chosen a poor IDE, let me show you the light"; emacs'
