#!/usr/bin/bash

# Only on terminals that support color
if test $(tput colors) -ge 8; then
	ERROR_COLOR="$(tput setab 1)"
	BRANCH_COLOR="$(tput setaf 0)"
	NO_COLOR="$(tput sgr0)"
else
	ERROR_COLOR=""
	BRANCH_COLOR=""
	NO_COLOR=""
fi

# Customize the prompt by adding the git branch

PS1="\$(print_last_failure)[\$(basename \$(pwd))\$(find_branch)]\\$ "
