#!/bin/bash

readonly INSTALLER_DIR="$(dirname $(readlink -f ${BASH_SOURCE[0]}))"
pushd ${INSTALLER_DIR} &> /dev/null

readonly ROOT_DIR=$(git root)
readonly STARTING_DIR="${ROOT_DIR}/home"

if [[ -z "${ROOT_DIR}" ]]; then
	echo "Unknown root folder; exiting"
	popd
	exit 1
fi

echo "Running symlink tool from ${ROOT_DIR}"

function hasTilde ()
{
	if [[ "${1: -1}" == "~" ]]; then
		return 0
	fi

	return 1
}

function isInvalidFile ()
{
	if hasTilde $1; then
		return 0
	fi

	return 1
}

function isInvalidDirectory ()
{
	if hasTilde $1; then
		return 0
	fi

	if [[ "$1" == "." ]]; then
		return 0
	fi

	if [[ "$1" == ".." ]]; then
		return 0
	fi

	return 1
}

function isSymlink ()
{
	if [[ "$(ls $1)" != "$(readlink -f $1)" ]]; then
		return 0
	fi

	return 1
}

function symlinkFolder ()
{
	for i in $(ls -a $1)
	do
		local fullPath=$1/$i
		local newPath="$HOME/${fullPath#"${STARTING_DIR}"}"
		if [[ -d "$fullPath" ]]; then
			if isInvalidDirectory $i; then
				continue
			fi

			mkdir -p $newPath
			symlinkFolder "$fullPath"
		else
			if isInvalidFile $i; then
				continue
			fi

			if isSymlink $fullPath; then
				cp -P $fullPath $newPath
			else
				ln -fs $fullPath $newPath
			fi

		fi
	done
}

symlinkFolder "${STARTING_DIR}"

popd &> /dev/null
